### ISSUE TITLE
support custom Overpass API endpoints

### ISSUE THREAD

**Issue by BCarroll524** [derhuerst/query-overpass#10]
Is it possible to set the url of the overpass api that is being queried? I have a local OSM server and would like to send the requests to that to allow for more requests per minute to come through. Thank you

**Comment by BCarroll524** [comment]
Nevermind, I have simply changed the `endpoint` in index.js to the URL I want to hit. However, I do think that would be a nice addition to add the option of setting the endpoint!

**Comment by derhuerst** [comment]
> Is it possible to set the url of the overpass api that is being queried?

Not yet, but that would be a cool addition; PR welcome!

> Nevermind, I have simply changed the `endpoint` in index.js to the URL I want to hit. However, I do think that would be a nice addition to add the option of setting the endpoint!

Yeah, changing source code of dependencies isn't convenient at all. Let's solve this once for all users.

I'd like to introduce an options parameter for this, similar to this: https://github.com/derhuerst/svg-world-map/blob/1f7fdf49448e912a017b50c830af4cd09aca635e/index.js#L27-L36

**Comment by BCarroll524** [comment]
Thank you for adding this!
